name: Build Multi-Architecture Docker Image

on:
  push:
    branches:
      - branchHTTPserver

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.yaroslavpon }}
          password: ${{ secrets.culPm62k:l }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Build and push multi-arch image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: yaroslavpon/http-server:latest
