name: Build and Compile

on:
  push:
    branches:
      - branchMake
  pull_request:
    branches:
      - branchMake

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up C++ build environment
        run: sudo apt-get install build-essential
      - name: Build the project
        run: make
				
			-	name: Build tarball
				run:	./autogen.sh	&&	./configure	&&	make	dist
		
			- name: Build Debian package
 		 		run: dpkg-buildpackage -us -uc
 		 	
 			- name: Run tests
  			run: make check


