name: Build and Push Docker Image

on:
  push:
    branches:
      - branchHTTPservMutli

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        architecture: [amd64, arm64]

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.yaroslavpon }}
          password: ${{ secrets.culPm62k:l }}

      - name: Build and push Docker image
        run: |
          docker buildx create --use
          docker buildx build --platform linux/${{ matrix.architecture }} -t your-dockerhub-username/http-server:${{ matrix.architecture }} --push .

      - name: Create Docker manifest
        run: |
          docker manifest create your-dockerhub-username/http-server:latest \
            --amend your-dockerhub-username/http-server:amd64 \
            --amend your-dockerhub-username/http-server:arm64
          docker manifest push your-dockerhub-username/http-server:latest

